[package]
name = "rost"
version = "0.1.0"
authors = ["Robochu <oleg.aprelikov@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
rand_pcg = "0.3.0"
